//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.ClothStock = new HashSet<ClothStock>();
        }
    
        public double Артикул { get; set; }
        public string Название { get; set; }
        public string Цвет { get; set; }
        public string Рисунок { get; set; }
        public string Состав { get; set; }
        public Nullable<double> Ширина_см { get; set; }
        public Nullable<double> Длина_см { get; set; }
        public Nullable<double> Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClothStock> ClothStock { get; set; }
    }
}
